Website/Models/PreferencesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newsery.DataTypes;
namespace Newsery.Website
{
    public class SelectedTag
    {
        public string Country { get; set; }
        public string Id { get; set; }
        public bool IsSelected { get; set; }
        public string Value { get; set; }
    }
    public class SelectedNewspaper
    {
        public string Country { get; set; }
        public string Id { get; set; }
        public bool IsSelected { get; set; }
        public string Name { get; set; }
    }
    public class PreferencesModel
    {
        public List<SelectedTag> SelectedTags { get; set; }
        public List<SelectedNewspaper> SelectedNewspapers { get; set; }
    }
}

Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


using System.Web.Mvc;
using Newsery.DataTypes;

namespace Newsery.Website.Controllers
{
    public class HomeController : Controller
    {
        private int _PageSize=20;
        public ActionResult Index()
        {
            //this line to prevent the browser from caching home page, the one which is opened when the user logs in
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            return RedirectToAction("All", new  { country="مصر"});
        }

       
        public ActionResult All(string country, string lastStoryId)
        {
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            SessionManager.SetCurrentCountry(country);
            if (lastStoryId == null)
                lastStoryId = "";
            if (Request.IsAjaxRequest())
            {
                return PartialView("ArabicStoryPagePartial", GetPaginatedStories(country,lastStoryId));
            }
            else
            {
                ViewBag.SelectedTag = "All";
                return View("Arabic", GetPaginatedStories(country, lastStoryId));
            }
          
        }
        public ActionResult Tag(string country, string tag, string lastStoryId)
        {
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            SessionManager.SetCurrentCountry(country);
            if (lastStoryId == null)
                lastStoryId = "";
            if (Request.IsAjaxRequest())
            {
                return PartialView("ArabicStoryPagePartial", GetPaginatedStories(country,tag, lastStoryId));
            }
            else
            {
                ViewBag.SelectedTag = tag;
                return View("Arabic", GetPaginatedStories(country,tag, lastStoryId));
            }
        } 
        private List<Story> GetPaginatedStories(string country,string lastStoryId)
        {
            List<Story> stories = NewsManager.GetFilteredStories(country).ToList();
            int startIndex;
            if (lastStoryId == "")
                startIndex = 0;
            else
            {
                startIndex=stories.FindIndex(s => s.Id == lastStoryId) + 1;
                
            }
            return stories.Skip(startIndex).Take(_PageSize).ToList();
        }

        private List<Story> GetPaginatedStories(string country,string tag, string lastStoryId)
        {

            List<Story> stories = NewsManager.GetFilteredStories(country,tag).ToList();
            int startIndex;
            if (lastStoryId == "")
                startIndex = 0;
            else
            {
                startIndex = stories.FindIndex(s => s.Id == lastStoryId) + 1;

            }
            return stories.Skip(startIndex).Take(_PageSize).ToList();
        }


    }
}

Website/Controllers/PreferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newsery.CassandraDataAccessLayer;
using Newsery.DataTypes;
using Newsery.Website;
namespace Newsery.Website.Controllers
{
    public class PreferencesController : Controller
    {
        //
        // GET: /Tags/

        public ActionResult Index()
        {
            PreferencesModel model = new PreferencesModel();
            model.SelectedTags = new List<SelectedTag>();
            Tag[] excludedTags = SessionManager.GetExcludedTags();
            List<Tag> allTags = NewsSroucesManager.GetTags();
            //display the tags ordered
            allTags = allTags.OrderBy(t => t.Order).ToList();
            foreach (Tag tag in allTags)
            {
                var v = from Tag t in excludedTags where t.Id == tag.Id select t;
                SelectedTag selected=new SelectedTag();
                selected.Value=tag.Value;
                selected.Id = tag.Id.ToString();
                selected.Country = tag.Country;
                if (v.Count<Tag>()> 0)
                selected.IsSelected = false;
                else
                    selected.IsSelected = true;
                model.SelectedTags.Add(selected);
            }
            model.SelectedNewspapers = new List<SelectedNewspaper>();
            Newspaper[] excludedNewspapers = SessionManager.GetExcludedNewspapers();
            List<Newspaper> allNewspapers = NewsSroucesManager.GetNewspapers();
            foreach (Newspaper newspaper in allNewspapers)
            {
                var v = from Newspaper n in excludedNewspapers where n.Id == newspaper.Id select n;
                SelectedNewspaper selected = new SelectedNewspaper();
                selected.Id = newspaper.Id.ToString();
                selected.Name = newspaper.Name;
                selected.Country = newspaper.Country;
                if (v.Count<Newspaper>() > 0)
                    selected.IsSelected = false;
                else
                    selected.IsSelected = true;
                model.SelectedNewspapers.Add(selected);
            }
            if ((string)Session["Country"] == "مصر")
                return View("Arabic",model);
            else
                throw new ApplicationException("Unsupported Country");
        }
        [HttpPost]
        public ActionResult Index(PreferencesModel model)
        {
            string[] excluededIds = (from SelectedTag selected in model.SelectedTags where selected.IsSelected == false select selected.Id).ToArray();
            List<Tag> allTags = NewsSroucesManager.GetTags();
            Tag[] excludedTags = (from Tag t in allTags where excluededIds.Contains(t.Id.ToString()) select t).ToArray();
            SessionManager.SetUserExcludedTags(excludedTags);
            
            string []excludedNewspapersIds = (from SelectedNewspaper selected in model.SelectedNewspapers where selected.IsSelected == false select selected.Id).ToArray();
            List<Newspaper>allNewspapers = NewsSroucesManager.GetNewspapers();
            Newspaper[]excludedNewspapers = (from Newspaper n in allNewspapers where excludedNewspapersIds.Contains(n.Id.ToString()) select n).ToArray();
            SessionManager.SetUserExcludedNewspapers(excludedNewspapers);
            
            return Content("تم الحفظ بنجاح");
        }

    }
}

Website/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newsery.DataTypes;

namespace Newsery.Website.Controllers
{
    public class StoryController : Controller
    {
        //
        // GET: /Story/

        public ActionResult Index(string country,string storyId)
        {
            Story requiredStory = NewsManager.GetStoryById(country,storyId);
            if (requiredStory != null)
                return View("Arabic", requiredStory);
            else
                return View("ArabicNotFound");
        }

    }
}

Website/Views/Preferences/Arabic.app.cshtml
@model Newsery.Website.PreferencesModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="description" content="آخر الأخبار من كل الصحف الإلكترونية" />
    <meta name="keywords" content="مصر,أخبار,أنباء,سياسة,رياضة,إقتصاد,ثقافة" />
    <meta charset="utf-8" />

    <link href="@Url.Content("~/Content/App 0.0.0.6.css")" rel="stylesheet" type="text/css" />
    <script src="/Scripts/jquery-2.0.3.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <title>إعدادات الأخبار</title>
</head>
<body dir="rtl" style="background-color: #EFEFEF;margin:0px;">
    <script type="text/javascript">
        function Success() {
            $("#updateResult").show();
        @*Wait for 1 seconds then redict the user to home page*@
            window.setTimeout(RedirectToHomePage, 1000);
        }
        function RedirectToHomePage() {
            window.location.replace("@Url.Action("Index", "Home", null, "http")");
    }
    </script>
    @using (Ajax.BeginForm("Index", "Preferences", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "updateResult", OnSuccess = "Success" }))
    {
        
            <div style="width: 100%; height: 45px; text-align:center;background-color:#333333;vertical-align:central;">
                <div id="SaveButtonBorders">
                <input type="submit" id="SaveButton"style="border:0px;"value="حـفـظ الإعـدادات"/>
                </div>
            </div>
            
   

        <div id="PreferencesMainContainer">
            @{Model.SelectedTags = Model.SelectedTags.OrderBy(t => t.Value).ToList();}

            <div style=" font-family: Droid; font-size: 15px; margin: 15px 0;color:#666666;">إختر تصنيفات الأخبار و مصادر الأخبار التي تهتم بمتابعتها</div>
            <div style="margin-bottom:15px; height: 20px;text-align:center;"><span id="updateResult" style="font-family: Droid; color: #29A8DF; font-size: 16px; display: none; border: 1px solid; border-radius: 3px; padding: 3pt;"></span></div>
            <div class="preferences_section_title" id ="SectionsToggle"><span id="SectionsIndicator" class="preferences_expanded"></span>الأقسام</div>
            <div style="text-align: right; padding: 0px 40px 0 0"; id="Sections">
                @for (int i = 0; i < Model.SelectedTags.Count; i++)
                {
                    <div class="preferences_checkbox">
                        @Html.CheckBoxFor(m => m.SelectedTags[i].IsSelected)
                        @*Use a hidden field to store the id only since this is the only field needed at the controller's side *@
                        @Html.HiddenFor(m => m.SelectedTags[i].Id)
                        @Model.SelectedTags[i].Value
                    </div>
                        
                }

                </div>
                <div class="preferences_section_title" id="SourcesToggle"><span id="SourcesIndicator" class="preferences_expanded"></span>مصادر الأخبار</div>

                @{Model.SelectedNewspapers = Model.SelectedNewspapers.OrderBy(n => n.Name).ToList();}
            <div style="text-align: right; padding: 0px 40px 0 0;" id="Sources">
                @for (int i = 0; i < Model.SelectedNewspapers.Count; i++)
                {
                    <div class="preferences_checkbox">
                        @Html.CheckBoxFor(m => m.SelectedNewspapers[i].IsSelected, new { @class = "tpot" })
                        @*Use a hidden field to store the id only since this is the only field needed at the controller's side *@
                        @Html.HiddenFor(m => m.SelectedNewspapers[i].Id)
                        @Model.SelectedNewspapers[i].Name
                    </div>
        

                }
                </div>
            </div>

       
    }

    <script type="text/javascript">

        
        var sourcesExpanded = true;
        var sectionsExpanded = true;
        $('div#SourcesToggle').click(function () {
            var sourcesIndicator = $('span#SourcesIndicator');
            if (sourcesExpanded) {
                sourcesIndicator.removeClass('preferences_expanded');
                sourcesIndicator.addClass('preferences_collapsed');
                sourcesExpanded = false;
            }
            else {
                sourcesIndicator.removeClass('preferences_collapsed');
                sourcesIndicator.addClass('preferences_expanded');
                sourcesExpanded = true;
            }
            $('div#Sources').toggle();
        });

        $('div#SectionsToggle').click(function () {
            var sectionsIndicator = $('span#SectionsIndicator');
            if (sectionsExpanded) {
                sectionsIndicator.removeClass('preferences_expanded');
                sectionsIndicator.addClass('preferences_collapsed');
                sectionsExpanded = false;
            }
            else {
                sectionsIndicator.removeClass('preferences_collapsed');
                sectionsIndicator.addClass('preferences_expanded');
                sectionsExpanded = true;
            }
            $('div#Sections').toggle();
        });

    </script>

    @*google analytics asynchronous script*@
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-42590272-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</body>
</html>

Website/Views/Preferences/Arabic.cshtml
@model Newsery.Website.PreferencesModel
@{
    ViewBag.Title = "إعدادات الأخبار";
    Layout = "~/Views/Shared/_ArabicLayout.cshtml";
}
<script type="text/javascript">
    function Success()
    {
        $("#updateResult").show(700);
        @*Wait for 3 seconds then redict the user to home page*@
        window.setTimeout(RedirectToHomePage, 3000);
        
    }
    function RedirectToHomePage()
    {
        window.location.replace("@Url.Action("Index", "Home",null,"http")");
    }
    </script>
@{Model.SelectedTags = Model.SelectedTags.OrderBy(t => t.Value).ToList();}
@using (Ajax.BeginForm("Index", "Preferences", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "updateResult" , OnSuccess="Success" }))
{
    <div style="border-bottom:solid 1px #29A8DF; border-top:solid 1px #29A8DF; height:30px;margin-top:10px; background-color:#FFFFFF;">
        <span style="float:right;font-family:GE_SS;font-size:16px; margin:4px;">إختر تصنيفات الأخبار و مصادر الأخبار التي تهتم بمتابعتها</span>
         <input type="submit" value=" حفظ الإعدادات" style="float:left; height:25px; background-color:#29A8DF; margin:2px 0 auto 10px; color:#FFFFFF; font-family:GE_SS_Bold;font-size:12px;" />
    </div>
    <div style="margin:15pt; height:12pt;"><span id="updateResult" style="font-family:GE_SS_Medium;color:#29A8DF;font-size:13pt; display:none;border:1px solid;border-radius:3px;padding:3pt;"></span></div>
    <div class="preferences_section_title">الأقسام</div>
    <div style="text-align: right; padding:0px 40px 0 0; margin:0 auto; width:600px;" >
        @for (int i = 0; i < Model.SelectedTags.Count; i++)
        {
            <div class="preferences_checkbox">
                @Html.CheckBoxFor(m => m.SelectedTags[i].IsSelected)
                @*Use a hidden field to store the id only since this is the only field needed at the controller's side *@
                @Html.HiddenFor(m => m.SelectedTags[i].Id)
            @Model.SelectedTags[i].Value
            </div>
                        
        }


        <div class="preferences_section_title">مصادر الأخبار</div>

        @{Model.SelectedNewspapers = Model.SelectedNewspapers.OrderBy(n => n.Name).ToList();}
        @for (int i = 0; i < Model.SelectedNewspapers.Count; i++)
        {
            <div class="preferences_checkbox">
                @Html.CheckBoxFor(m => m.SelectedNewspapers[i].IsSelected, new { @class = "tpot" })
                @*Use a hidden field to store the id only since this is the only field needed at the controller's side *@
                @Html.HiddenFor(m => m.SelectedNewspapers[i].Id)
                @Model.SelectedNewspapers[i].Name
            </div>
        

        }
    </div>
    
   
        
}

@section TopAd
{
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-5787753563620608"
     data-ad-slot="3403929258"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
}


@section LeftAd
{
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-5787753563620608"
     data-ad-slot="6357395652"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
}
@section RightAd
{
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-5787753563620608"
     data-ad-slot="7834128856"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
    }

Website/Views/Preferences/Arabic.mobile.cshtml
@model Newsery.Website.PreferencesModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="description" content="آخر الأخبار من كل الصحف الإلكترونية" />
    <meta name="keywords" content="مصر,أخبار,أنباء,سياسة,رياضة,إقتصاد,ثقافة" />
    <meta charset="utf-8" />

    <link href="@Url.Content("~/Content/ArabicMobile.css")" rel="stylesheet" type="text/css" />
    <script src="/Scripts/jquery-2.0.3.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <title>إعدادات الأخبار</title>
</head>
<body dir="rtl" style="max-width: 600px; background-color: #EFEFEF;">
    <script type="text/javascript">
        function Success() {
            $("#updateResult").show();
        @*Wait for 2 seconds then redict the user to home page*@
            window.setTimeout(RedirectToHomePage, 2000);
        }
        function RedirectToHomePage() {
            window.location.replace("@Url.Action("Index", "Home", null, "http")");
    }
    </script>
    @using (Ajax.BeginForm("Index", "Preferences", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "updateResult", OnSuccess = "Success" }))
    {
        <div id="Header">
            <div style="width: 100%; height: 50px;">
                <a href="@Url.Action("Index", "Home", null, "http")" title="الصفحة الرئيسة" style="margin-top:6px;width:215px;height:39px; float:left;"><span id="Logo"></span></a>
                <input type="submit" id="SaveButton"style="border:0px;"value=""/>
                <span style="float: right; width: 1px; height: 36px; background-color: #3B3B3B; margin: 7px 13px 0 0;"></span>
                <span style="float: right; width: 1px; height: 36px; background-color: #212121; margin-top: 7px;"></span>
            </div>
            <div style="width: 100%; height: 2px; background-color: #29A8DF;"></div>
        </div>

        <div id="MainContainer">
            @{Model.SelectedTags = Model.SelectedTags.OrderBy(t => t.Value).ToList();}

            <div style=" font-family: GE_SS; font-size: 16px; margin: 15px 0;color:#666666;">إختر تصنيفات الأخبار و مصادر الأخبار التي تهتم بمتابعتها</div>
            <div style="margin-bottom:15px; height: 20px;text-align:center;"><span id="updateResult" style="font-family: GE_SS_Medium; color: #29A8DF; font-size: 16px; display: none; border: 1px solid; border-radius: 3px; padding: 3pt;"></span></div>
            <div class="preferences_section_title" id ="SectionsToggle"><span id="SectionsIndicator" class="preferences_expanded"></span>الأقسام</div>
            <div style="text-align: right; padding: 0px 40px 0 0"; id="Sections">
                @for (int i = 0; i < Model.SelectedTags.Count; i++)
                {
                    <div class="preferences_checkbox">
                        @Html.CheckBoxFor(m => m.SelectedTags[i].IsSelected)
                        @*Use a hidden field to store the id only since this is the only field needed at the controller's side *@
                        @Html.HiddenFor(m => m.SelectedTags[i].Id)
                        @Model.SelectedTags[i].Value
                    </div>
                        
                }

                </div>
                <div class="preferences_section_title" id="SourcesToggle"><span id="SourcesIndicator" class="preferences_expanded"></span>مصادر الأخبار</div>

                @{Model.SelectedNewspapers = Model.SelectedNewspapers.OrderBy(n => n.Name).ToList();}
            <div style="text-align: right; padding: 0px 40px 0 0;" id="Sources">
                @for (int i = 0; i < Model.SelectedNewspapers.Count; i++)
                {
                    <div class="preferences_checkbox">
                        @Html.CheckBoxFor(m => m.SelectedNewspapers[i].IsSelected, new { @class = "tpot" })
                        @*Use a hidden field to store the id only since this is the only field needed at the controller's side *@
                        @Html.HiddenFor(m => m.SelectedNewspapers[i].Id)
                        @Model.SelectedNewspapers[i].Name
                    </div>
        

                }
                </div>
            </div>

       
    }

    <script type="text/javascript">
        function SetLayout() {
            var windowWidth = $(window).width();
            var bodyWidth = $('body').width();

            var mainContainerMargin = (windowWidth - bodyWidth) / 2;

            $('div#MainContainer').css('right', mainContainerMargin);
            $('div#MainContainer').css('left', mainContainerMargin);
            $('div#Header').css('left', mainContainerMargin);
            $('div#Header').css('right', mainContainerMargin);
        }
        $(document).ready(SetLayout);
        $(window).resize(SetLayout);
        var sourcesExpanded = true;
        var sectionsExpanded = true;
        $('div#SourcesToggle').click(function () {
            var sourcesIndicator = $('span#SourcesIndicator');
            if (sourcesExpanded) {
                sourcesIndicator.removeClass('preferences_expanded');
                sourcesIndicator.addClass('preferences_collapsed');
                sourcesExpanded = false;
            }
            else {
                sourcesIndicator.removeClass('preferences_collapsed');
                sourcesIndicator.addClass('preferences_expanded');
                sourcesExpanded = true;
            }
            $('div#Sources').toggle();
        });

        $('div#SectionsToggle').click(function () {
            var sectionsIndicator = $('span#SectionsIndicator');
            if (sectionsExpanded) {
                sectionsIndicator.removeClass('preferences_expanded');
                sectionsIndicator.addClass('preferences_collapsed');
                sectionsExpanded = false;
            }
            else {
                sectionsIndicator.removeClass('preferences_collapsed');
                sectionsIndicator.addClass('preferences_expanded');
                sectionsExpanded = true;
            }
            $('div#Sections').toggle();
        });

    </script>

    @*google analytics asynchronous script*@
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-42590272-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</body>
</html>

Website/Views/Shared/ArabicStoryPagePartial.cshtml
@model List<Newsery.DataTypes.Story>
@using Newsery.DataTypes

@for (int i = 0; i < Model.Count; i++)
{
    ViewDataDictionary data=new ViewDataDictionary();
    if (i % 2 == 0)
    {   data.Add("Direction", "right");}
    else
    {
        data.Add("Direction", "left");
    }
    @(Html.Partial("ArabicStoryPartialSmall", Model[i],data))

}

@if (Model.Count > 0)
{
    <input type="hidden"  class="LastStoryId" value="@Model[Model.Count - 1].Id" />
}

Website/Views/Shared/ArabicStoryPartialSmall.mobile.cshtml
@model Newsery.DataTypes.Story

<div class="small_story">
    <div>
        <div class="external_link_div"><a href="@Model.Articles[0].Url" target="_blank" ><span class="external_link"></span></a></div>
        <div >
            @{
                string sharingurl = Url.Action("Index", "Story", new { country = "مصر", storyId = Model.Id.ToString() }, "http"); 
            }
            <a href="@sharingurl" class="story_title" target="_blank">@Model.Articles[0].Title</a>
        </div>
    </div>
    @{
        string time;
        int totalHoursElapsed = (int)(DateTime.UtcNow - Model.Date).TotalHours;
        if (totalHoursElapsed > 24)
        {
            time = Model.Date.ToString("dd MMMM yyyy", System.Globalization.CultureInfo.GetCultureInfo("ar-Eg"));
        }
        else if (totalHoursElapsed > 0)
        {
            if (totalHoursElapsed == 1)
            {
                time = "منذ ساعة";
            }
            else if (totalHoursElapsed == 2)
            {
                time = "منذ ساعتان";
            }
            else if (totalHoursElapsed > 2 && totalHoursElapsed < 11)
            {
                time = " منذ " + totalHoursElapsed.ToString() + " ساعات ";
            }
            else
            {
                time = "منذ " + totalHoursElapsed.ToString() + " ساعة";

            }
        }
        else
        {
            int totalMinutesElapsed = (int)(DateTime.UtcNow - Model.Date).TotalMinutes;
            time = " منذ " + totalMinutesElapsed.ToString() + " دقيقة";
        }
    }
    <div class="small_story_info">
        <div class="news_detail"><div class="newspaper_icon"></div><div class="small_story_newspaper">@Model.Articles[0].NewsPaper</div></div>
        <div class="news_detail"><div class="time_icon"></div><div class="small_story_time">@time</div></div>
        <div class="news_detail">
            @{
                string stringCount = Model.Articles.Count.ToString();
                if (Model.Articles.Count > 2 && Model.Articles.Count < 11)
                {
                <div class="sources_count">&nbsp;(@stringCount)&nbsp; مصادر  </div>
                }
                else
                {
                <div class="sources_count">&nbsp;(@stringCount)&nbsp; مصدر</div>
                }
            }
        </div>
    </div>
    <div class="small_story_separator"></div>
</div>

Website/Views/Story/Arabic.cshtml
@model Newsery.DataTypes.Story
@using Newsery.DataTypes;

@{
    ViewBag.Title = "Newsery-" + Model.Articles[0].Title;
    Layout = "~/Views/Shared/_ArabicLayout.cshtml";
}


<div style="float:right;text-align:right; ">
@foreach (Article a in Model.Articles)
{
    @Html.Partial("ArabicStoryPartialLarge", a);
}
    </div>
<div style="float:right;margin-top:10px;">
    @{
      string sharingurl = Url.Action("Index", "Story", new {country="مصر" ,storyId=Model.Id.ToString()},"http");
      <iframe src="//www.facebook.com/plugins/like.php?href=@sharingurl&amp;width=65&amp;height=65&amp;colorscheme=light&amp;layout=box_count&amp;action=like&amp;show_faces=false&amp;send=false&amp;appId=547996471923788" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:55px; height:65px;" allowTransparency="true"></iframe>
     <div><a href="https://twitter.com/share" class="twitter-share-button twitter-large" data-url="@sharingurl" data-lang="ar"  	data-count="vertical" >غرد</a></div>
        <div class="g-plusone" data-size="tall" data-href="@sharingurl"></div>
    }
</div>





@section TopAd
{
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-5787753563620608"
     data-ad-slot="3403929258"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
}
@section LeftAd
{
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-5787753563620608"
     data-ad-slot="6357395652"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
}
@section RightAd
{
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-5787753563620608"
     data-ad-slot="7834128856"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
    }
 
@*Twitter sharing code*@
<script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');</script>
@*google plus sharing code*@
<script type="text/javascript">
    window.___gcfg = { lang: 'ar' };

    (function () {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
</script>